import {Body,Controller,Delete,Get,Header,Param,Patch,Query,Post,Req,UseGuards} from "@nestjs/common";import {ApiBearerAuth,ApiTags} from "@nestjs/swagger";import {AuthGuard} from "./auth.guard";import {AdvancedService} from "./advanced.service";
@ApiTags("advanced") @ApiBearerAuth() @UseGuards(AuthGuard) @Controller() export class AdvancedController{constructor(private s:AdvancedService){}private u(r:any){return r.user.sub}
 @Get("workspaces/:w/members") members(@Req()r:any,@Param("w")w:string){return this.s.members(this.u(r),w)} @Post("workspaces/:w/members") addMember(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.addMember(this.u(r),w,b)} @Patch("workspaces/:w/members/:id") updateMember(@Req()r:any,@Param("w")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateMemberRole(this.u(r),w,id,b)} @Delete("workspaces/:w/members/:id") removeMember(@Req()r:any,@Param("w")w:string,@Param("id")id:string){return this.s.removeMember(this.u(r),w,id)}
 @Get("workspaces/:w/shared-expenses") shared(@Req()r:any,@Param("w")w:string){return this.s.shared(this.u(r),w)} @Post("workspaces/:w/shared-expenses") createShared(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.createShared(this.u(r),w,b)} @Patch("workspaces/:w/shared-expenses/splits/:id/settle") settle(@Req()r:any,@Param("w")w:string,@Param("id")id:string){return this.s.settleSplit(this.u(r),w,id)}
 @Get("workspaces/:w/reports/summary") report(@Req()r:any,@Param("w")w:string,@Query("period")period?:string){return this.s.report(this.u(r),w,period)} @Get("workspaces/:w/export/csv") @Header("Content-Type","text/csv") csv(@Req()r:any,@Param("w")w:string){return this.s.csv(this.u(r),w)} @Post("workspaces/:w/import/preview") preview(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.importPreview(this.u(r),w,b)}
 @Get("workspaces/:w/evidence") evidence(@Req()r:any,@Param("w")w:string){return this.s.evidence(this.u(r),w)} @Post("workspaces/:w/evidence") addEvidence(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.registerEvidence(this.u(r),w,b)}
 @Delete("workspaces/:w/evidence/:id") deleteEvidence(@Req()r:any,@Param("w")w:string,@Param("id")id:string){return this.s.deleteEvidence(this.u(r),w,id)}
 @Get("workspaces/:w/recurring") recurring(@Req()r:any,@Param("w")w:string){return this.s.recurring(this.u(r),w)} @Post("workspaces/:w/recurring") createRecurring(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.createRecurring(this.u(r),w,b)}
 @Get("notifications") notifications(@Req()r:any){return this.s.notifications(this.u(r))} @Patch("notifications/:id/read") read(@Req()r:any,@Param("id")id:string){return this.s.markRead(this.u(r),id)}
 @Get("workspaces/:w/preferences") prefs(@Req()r:any,@Param("w")w:string){return this.s.preferences(this.u(r),w)} @Patch("workspaces/:w/preferences") updatePrefs(@Req()r:any,@Param("w")w:string,@Body()b:any){return this.s.updatePreferences(this.u(r),w,b)}
 @Post("workspaces/:w/ai/ask") ai(@Req()r:any,@Param("w")w:string,@Body()b:{question:string}){return this.s.askAi(this.u(r),w,b.question??"")}
 @Get("plans") plans(){return this.s.plans()} @Post("workspaces/:w/subscription") subscribe(@Req()r:any,@Param("w")w:string,@Body()b:{planCode:string}){return this.s.subscribe(this.u(r),w,b.planCode)} @Post("admin/plans/seed") seed(@Req()r:any){return this.s.seedPlans(this.u(r))} @Get("admin/summary") admin(@Req()r:any){return this.s.admin(this.u(r))}}
