import {BadRequestException,Injectable,UnauthorizedException} from "@nestjs/common"; import {JwtService} from "@nestjs/jwt"; import {prisma} from "@ledgermate/database"; import {compare,hash} from "bcryptjs";import {createHash,randomBytes} from "node:crypto";
const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
@Injectable() export class AuthService{constructor(private jwt:JwtService){}
 async register(input:{name:string;email:string;password:string;phone?:string;country?:string;avatarUrl?:string}){const email=input.email.trim().toLowerCase();if(input.name?.trim().length<2)throw new BadRequestException("Full name is required");if(input.password.length<8)throw new BadRequestException("Password must contain at least 8 characters");if(input.avatarUrl&&input.avatarUrl.length>1_500_000)throw new BadRequestException("Profile image is too large");if(await prisma.user.findUnique({where:{email}}))throw new BadRequestException("Email is already registered");const user=await prisma.user.create({data:{name:input.name.trim(),email,passwordHash:await hash(input.password,12),phone:input.phone?.trim()||null,country:input.country?.trim()||null,avatarUrl:input.avatarUrl||null},select:{id:true,name:true,email:true,phone:true,country:true,avatarUrl:true}});const invites=await prisma.workspaceInvite.findMany({where:{email}});if(invites.length)await prisma.$transaction([prisma.workspaceMember.createMany({data:invites.map(i=>({workspaceId:i.workspaceId,userId:user.id,role:i.role})),skipDuplicates:true}),prisma.workspaceInvite.deleteMany({where:{email}})]);return {user,accessToken:await this.jwt.signAsync({sub:user.id,email:user.email})}}
 async login(input:{email:string;password:string}){const user=await prisma.user.findUnique({where:{email:input.email.trim().toLowerCase()}});if(!user||!await compare(input.password,user.passwordHash))throw new UnauthorizedException("Invalid email or password");return {user:{id:user.id,name:user.name,email:user.email,phone:user.phone,country:user.country,avatarUrl:user.avatarUrl},accessToken:await this.jwt.signAsync({sub:user.id,email:user.email})}}
 async forgotPassword(input:{email:string}){const user=await prisma.user.findUnique({where:{email:input.email.trim().toLowerCase()}});let developmentToken:string|undefined;if(user){const raw=randomBytes(32).toString("hex");await prisma.passwordResetToken.create({data:{userId:user.id,tokenHash:tokenHash(raw),expiresAt:new Date(Date.now()+15*60_000)}});if(process.env.NODE_ENV!=="production")developmentToken=raw}return {message:"If that email exists, password reset instructions have been created.",developmentToken}}
 async resetPassword(input:{token:string;password:string}){if(input.password.length<8)throw new BadRequestException("Password must contain at least 8 characters");const row=await prisma.passwordResetToken.findUnique({where:{tokenHash:tokenHash(input.token)}});if(!row||row.usedAt||row.expiresAt<new Date())throw new BadRequestException("Reset token is invalid or expired");await prisma.$transaction([prisma.user.update({where:{id:row.userId},data:{passwordHash:await hash(input.password,12)}}),prisma.passwordResetToken.update({where:{id:row.id},data:{usedAt:new Date()}})]);return {message:"Password updated. You can now sign in."}}
 async profile(userId:string){const user=await prisma.user.findUnique({where:{id:userId},select:{id:true,name:true,email:true,phone:true,country:true,avatarUrl:true}});if(!user)throw new UnauthorizedException();return user}
 async updateProfile(userId:string,input:{name?:string;phone?:string;country?:string;avatarUrl?:string|null}){if(input.name!==undefined&&input.name.trim().length<2)throw new BadRequestException("Full name is required");if(input.avatarUrl&&input.avatarUrl.length>2_500_000)throw new BadRequestException("Profile image is too large");return prisma.user.update({where:{id:userId},data:{...(input.name!==undefined?{name:input.name.trim()}:{}),...(input.phone!==undefined?{phone:input.phone.trim()||null}:{}),...(input.country!==undefined?{country:input.country.trim()||null}:{}),...(input.avatarUrl!==undefined?{avatarUrl:input.avatarUrl||null}:{})},select:{id:true,name:true,email:true,phone:true,country:true,avatarUrl:true}})}
 async changePassword(userId:string,input:{currentPassword:string;newPassword:string}){if(input.newPassword?.length<8)throw new BadRequestException("New password must contain at least 8 characters");const user=await prisma.user.findUnique({where:{id:userId}});if(!user||!await compare(input.currentPassword??"",user.passwordHash))throw new UnauthorizedException("Current password is incorrect");await prisma.user.update({where:{id:userId},data:{passwordHash:await hash(input.newPassword,12)}});return {message:"Password changed successfully."}}
}
