import {BadRequestException,ForbiddenException,Injectable} from "@nestjs/common";
import {prisma} from "@ledgermate/database";
import {createBudgetSchema,createKhataEntrySchema,createLoanSchema,createPartySchema,createSalaryProfileSchema,createSavingsGoalSchema} from "@ledgermate/validation";

@Injectable()
export class Phase2Service{
 private async member(userId:string,workspaceId:string,write=false){const member=await prisma.workspaceMember.findUnique({where:{workspaceId_userId:{workspaceId,userId}}});if(!member)throw new ForbiddenException("Workspace access denied");if(write&&["VIEWER","AUDITOR"].includes(member.role))throw new ForbiddenException("Role cannot modify finance records");return member}
 async parties(userId:string,w:string){await this.member(userId,w);const parties=await prisma.party.findMany({where:{workspaceId:w,isActive:true},include:{entries:true},orderBy:{name:"asc"}});return parties.map(p=>{const given=p.entries.filter(e=>e.direction==="GIVEN").reduce((s,e)=>s+Number(e.amount),0),received=p.entries.filter(e=>e.direction==="RECEIVED").reduce((s,e)=>s+Number(e.amount),0);const {entries,...party}=p;return {...party,totalGiven:given,totalReceived:received,balance:given-received}})}
 async createParty(userId:string,w:string,raw:unknown){await this.member(userId,w,true);const d=createPartySchema.parse(raw);return prisma.party.create({data:{...d,email:d.email||null,workspaceId:w}})}
 async updateParty(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);const existing=await prisma.party.findFirst({where:{id,workspaceId:w}});if(!existing)throw new BadRequestException("Party not found");const d=createPartySchema.partial().parse(raw);return prisma.party.update({where:{id},data:{...d,email:d.email||undefined}})}
 async deleteParty(userId:string,w:string,id:string){await this.member(userId,w,true);const existing=await prisma.party.findFirst({where:{id,workspaceId:w}});if(!existing)throw new BadRequestException("Party not found");return prisma.party.update({where:{id},data:{isActive:false}})}
 async khataEntries(userId:string,w:string){await this.member(userId,w);return prisma.khataEntry.findMany({where:{workspaceId:w},include:{party:true},orderBy:{date:"desc"}})}
 async createKhataEntry(userId:string,w:string,raw:unknown){await this.member(userId,w,true);const d=createKhataEntrySchema.parse(raw);if(!await prisma.party.findFirst({where:{id:d.partyId,workspaceId:w}}))throw new BadRequestException("Party does not belong to workspace");return prisma.$transaction(async db=>{const entry=await db.khataEntry.create({data:{...d,workspaceId:w,createdById:userId}});await db.auditLog.create({data:{workspaceId:w,actorId:userId,action:"CREATED",entityType:"KhataEntry",entityId:entry.id,newValue:JSON.parse(JSON.stringify(d))}});return entry})}
 async updateKhata(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);if(!await prisma.khataEntry.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Khata entry not found");const d=createKhataEntrySchema.partial().parse(raw);return prisma.khataEntry.update({where:{id},data:d})}
 async deleteKhata(userId:string,w:string,id:string){await this.member(userId,w,true);if(!await prisma.khataEntry.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Khata entry not found");return prisma.khataEntry.delete({where:{id}})}
 async loans(userId:string,w:string){await this.member(userId,w);return prisma.loan.findMany({where:{workspaceId:w},include:{party:true},orderBy:{createdAt:"desc"}})}
 async createLoan(userId:string,w:string,raw:unknown){await this.member(userId,w,true);const d=createLoanSchema.parse(raw);if(d.partyId&&!await prisma.party.findFirst({where:{id:d.partyId,workspaceId:w}}))throw new BadRequestException("Party does not belong to workspace");return prisma.loan.create({data:{...d,workspaceId:w}})}
 async updateLoan(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);if(!await prisma.loan.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Loan not found");return prisma.loan.update({where:{id},data:createLoanSchema.partial().parse(raw)})}
 async deleteLoan(userId:string,w:string,id:string){await this.member(userId,w,true);if(!await prisma.loan.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Loan not found");return prisma.loan.delete({where:{id}})}
 async payLoan(userId:string,w:string,id:string,amount:number){await this.member(userId,w,true);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException("Payment must be positive");const loan=await prisma.loan.findFirst({where:{id,workspaceId:w}});if(!loan)throw new BadRequestException("Loan not found");const paid=Number(loan.totalPaid)+amount,total=Number(loan.principal)*(1+Number(loan.interestRate)/100);return prisma.loan.update({where:{id},data:{totalPaid:paid,status:paid>=total?"PAID":loan.status}})}
 async budgets(userId:string,w:string){await this.member(userId,w);const [rows,expenses]=await Promise.all([prisma.budget.findMany({where:{workspaceId:w,isActive:true},orderBy:{createdAt:"desc"}}),prisma.transaction.findMany({where:{workspaceId:w,type:{in:["EXPENSE","FEE","INTEREST"]},status:"CLEARED",archivedAt:null},include:{category:true}})]);return rows.map(b=>{const actual=expenses.filter(t=>t.date>=b.startsAt&&(!b.endsAt||t.date<=b.endsAt)&&t.category?.name.toLowerCase()===b.category.toLowerCase()).reduce((s,t)=>s+Number(t.amount),0),amount=Number(b.amount),usedPercent=amount?Math.round(actual/amount*100):0;return {...b,actual,remaining:amount-actual,usedPercent,health:usedPercent>=100?"OVER BUDGET":usedPercent>=90?"CRITICAL":usedPercent>=b.threshold?"WARNING":"SAFE"}})}
 async createBudget(userId:string,w:string,raw:unknown){await this.member(userId,w,true);return prisma.budget.create({data:{...createBudgetSchema.parse(raw),workspaceId:w}})}
 async updateBudget(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);if(!await prisma.budget.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Budget not found");return prisma.budget.update({where:{id},data:createBudgetSchema.partial().parse(raw)})}
 async deleteBudget(userId:string,w:string,id:string){await this.member(userId,w,true);if(!await prisma.budget.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Budget not found");return prisma.budget.update({where:{id},data:{isActive:false}})}
 async goals(userId:string,w:string){await this.member(userId,w);return prisma.savingsGoal.findMany({where:{workspaceId:w},orderBy:{createdAt:"desc"}})}
 async createGoal(userId:string,w:string,raw:unknown){await this.member(userId,w,true);const d=createSavingsGoalSchema.parse(raw);return prisma.savingsGoal.create({data:{...d,workspaceId:w,isCompleted:d.savedAmount>=d.targetAmount}})}
 async updateGoal(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);const goal=await prisma.savingsGoal.findFirst({where:{id,workspaceId:w}});if(!goal)throw new BadRequestException("Savings goal not found");const d=createSavingsGoalSchema.partial().parse(raw),target=Number(d.targetAmount??goal.targetAmount),saved=Number(d.savedAmount??goal.savedAmount);return prisma.savingsGoal.update({where:{id},data:{...d,isCompleted:saved>=target}})}
 async deleteGoal(userId:string,w:string,id:string){await this.member(userId,w,true);if(!await prisma.savingsGoal.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Savings goal not found");return prisma.savingsGoal.delete({where:{id}})}
 async contribute(userId:string,w:string,id:string,amount:number){await this.member(userId,w,true);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException("Contribution must be positive");const goal=await prisma.savingsGoal.findFirst({where:{id,workspaceId:w}});if(!goal)throw new BadRequestException("Savings goal not found");const saved=Number(goal.savedAmount)+amount;return prisma.savingsGoal.update({where:{id},data:{savedAmount:saved,isCompleted:saved>=Number(goal.targetAmount)}})}
 async salaries(userId:string,w:string){await this.member(userId,w);return prisma.salaryProfile.findMany({where:{workspaceId:w,isActive:true},orderBy:{createdAt:"desc"}})}
 async createSalary(userId:string,w:string,raw:unknown){await this.member(userId,w,true);return prisma.salaryProfile.create({data:{...createSalaryProfileSchema.parse(raw),workspaceId:w}})}
 async updateSalary(userId:string,w:string,id:string,raw:any){await this.member(userId,w,true);if(!await prisma.salaryProfile.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Salary profile not found");return prisma.salaryProfile.update({where:{id},data:createSalaryProfileSchema.partial().parse(raw)})}
 async deleteSalary(userId:string,w:string,id:string){await this.member(userId,w,true);if(!await prisma.salaryProfile.findFirst({where:{id,workspaceId:w}}))throw new BadRequestException("Salary profile not found");return prisma.salaryProfile.update({where:{id},data:{isActive:false}})}
}
