import {Body,Controller,Delete,Get,Param,Patch,Post,Req,UseGuards} from "@nestjs/common";
import {ApiBearerAuth,ApiTags} from "@nestjs/swagger";import {AuthGuard} from "./auth.guard";import {Phase2Service} from "./phase2.service";
@ApiTags("phase-2") @ApiBearerAuth() @UseGuards(AuthGuard) @Controller("workspaces/:workspaceId")
export class Phase2Controller{constructor(private s:Phase2Service){}private u(r:any){return r.user.sub}
 @Get("parties") parties(@Req()r:any,@Param("workspaceId")w:string){return this.s.parties(this.u(r),w)} @Post("parties") createParty(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createParty(this.u(r),w,b)} @Patch("parties/:id") updateParty(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateParty(this.u(r),w,id,b)} @Delete("parties/:id") deleteParty(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteParty(this.u(r),w,id)}
 @Get("khata") khata(@Req()r:any,@Param("workspaceId")w:string){return this.s.khataEntries(this.u(r),w)} @Post("khata") createKhata(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createKhataEntry(this.u(r),w,b)} @Patch("khata/:id") updateKhata(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateKhata(this.u(r),w,id,b)} @Delete("khata/:id") deleteKhata(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteKhata(this.u(r),w,id)}
 @Get("loans") loans(@Req()r:any,@Param("workspaceId")w:string){return this.s.loans(this.u(r),w)} @Post("loans") createLoan(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createLoan(this.u(r),w,b)} @Patch("loans/:id") updateLoan(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateLoan(this.u(r),w,id,b)} @Delete("loans/:id") deleteLoan(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteLoan(this.u(r),w,id)} @Patch("loans/:id/payment") payLoan(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:{amount:number}){return this.s.payLoan(this.u(r),w,id,Number(b.amount))}
 @Get("budgets") budgets(@Req()r:any,@Param("workspaceId")w:string){return this.s.budgets(this.u(r),w)} @Post("budgets") createBudget(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createBudget(this.u(r),w,b)} @Patch("budgets/:id") updateBudget(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateBudget(this.u(r),w,id,b)} @Delete("budgets/:id") deleteBudget(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteBudget(this.u(r),w,id)}
 @Get("savings") goals(@Req()r:any,@Param("workspaceId")w:string){return this.s.goals(this.u(r),w)} @Post("savings") createGoal(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createGoal(this.u(r),w,b)} @Patch("savings/:id") updateGoal(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateGoal(this.u(r),w,id,b)} @Delete("savings/:id") deleteGoal(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteGoal(this.u(r),w,id)} @Patch("savings/:id/contribution") contribute(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:{amount:number}){return this.s.contribute(this.u(r),w,id,Number(b.amount))}
 @Get("salary") salaries(@Req()r:any,@Param("workspaceId")w:string){return this.s.salaries(this.u(r),w)} @Post("salary") createSalary(@Req()r:any,@Param("workspaceId")w:string,@Body()b:unknown){return this.s.createSalary(this.u(r),w,b)} @Patch("salary/:id") updateSalary(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string,@Body()b:any){return this.s.updateSalary(this.u(r),w,id,b)} @Delete("salary/:id") deleteSalary(@Req()r:any,@Param("workspaceId")w:string,@Param("id")id:string){return this.s.deleteSalary(this.u(r),w,id)}
}
