import {existsSync,copyFileSync,readFileSync,writeFileSync,readdirSync,statSync,rmSync} from "node:fs";import {basename,join} from "node:path";import {execFileSync,spawnSync} from "node:child_process";import os from "node:os";
let javaHome=process.env.JAVA_HOME;if(!javaHome||!existsSync(javaHome)){try{javaHome=execFileSync("/usr/libexec/java_home",{encoding:"utf8"}).trim()}catch{javaHome=undefined}}
const results="automation/reports/allure-results";
for(const file of readdirSync(results))if(/^(api|ui|bdd|performance)-/.test(file))rmSync(join(results,file),{force:true,recursive:true});
function prefixSources(value,prefix){if(!value||typeof value!=="object")return;if(Array.isArray(value)){value.forEach(x=>prefixSources(x,prefix));return}if(typeof value.source==="string"&&!value.source.startsWith(`${prefix}-`))value.source=`${prefix}-${value.source}`;Object.values(value).forEach(x=>prefixSources(x,prefix))}
for(const suite of ["api","ui","bdd","performance"]){const saved=suite==="performance"?"automation/reports/performance-allure-results":`automation/reports/allure-${suite}-results`,nested=join(results,suite),dir=existsSync(saved)?saved:nested;if(!existsSync(dir))continue;const sourceFiles=readdirSync(dir),latest=new Map();for(const file of sourceFiles.filter(x=>x.endsWith("-result.json"))){const json=JSON.parse(readFileSync(join(dir,file),"utf8")),key=json.historyId??json.fullName??json.name,previous=latest.get(key);if(!previous||Number(json.stop??0)>previous.stop)latest.set(key,{file,stop:Number(json.stop??0)})}const selected=new Set([...latest.values()].map(x=>x.file));for(const file of sourceFiles){const source=join(dir,file);if(!statSync(source).isFile()||["environment.properties","executor.json","categories.json"].includes(file)||file.endsWith("-result.json")&&!selected.has(file))continue;const target=join(results,`${suite}-${basename(file)}`);if(file.endsWith(".json")){const json=JSON.parse(readFileSync(source,"utf8"));prefixSources(json,suite);writeFileSync(target,JSON.stringify(json))}else copyFileSync(source,target)}}
function collectAttachments(value,out=[]){if(!value||typeof value!=="object")return out;if(Array.isArray(value)){value.forEach(x=>collectAttachments(x,out));return out}if(Array.isArray(value.attachments))out.push(...value.attachments);Object.entries(value).forEach(([key,x])=>key!=="attachments"&&collectAttachments(x,out));return out}
function categoryOf(name=""){const n=name.toLowerCase();if(/invalid|unauthor|unknown|blocked|short|negative|wrong|missing/.test(n))return"negative";if(/health|login|register|dashboard|navigation|smoke/.test(n))return"smoke";return"regression"}
const merged=readdirSync(results).filter(f=>f.endsWith(".json")),resultFiles=new Map(),resultByUuid=new Map();
for(const file of merged.filter(f=>f.endsWith("-result.json"))){const json=JSON.parse(readFileSync(join(results,file),"utf8"));resultFiles.set(file,json);resultByUuid.set(json.uuid,{file,json})}
for(const file of merged.filter(f=>f.endsWith("-container.json"))){const container=JSON.parse(readFileSync(join(results,file),"utf8")),attachments=collectAttachments(container);for(const child of container.children??[]){const result=resultByUuid.get(child);if(result)result.json.attachments=[...(result.json.attachments??[]),...attachments]}writeFileSync(join(results,file),JSON.stringify(container))}
for(const {file,json} of resultByUuid.values()){const all=collectAttachments(json),seen=new Set(),category=categoryOf(json.name);json.attachments=all.filter(a=>["image/png","video/webm","application/vnd.allure.playwright-trace","application/json"].includes(a.type)&&!seen.has(a.source)&&seen.add(a.source));const epic=file.startsWith("api-")?"API":file.startsWith("ui-")?"UI":file.startsWith("performance-")?"Performance":"BDD";json.labels=[...(json.labels??[]).filter(x=>!["tag","epic","parentSuite"].includes(x.name)),{name:"tag",value:category},{name:"epic",value:epic},{name:"parentSuite",value:epic}];writeFileSync(join(results,file),JSON.stringify(json))}
writeFileSync(`${results}/environment.properties`,[`Product=LedgerMate 360`,`Project=Complete Product Automation`,`Report.Owner=Raja Haroon Jamal`,`Designation=Sr QA Automation`,`Environment=${process.env.TEST_ENV??"local"}`,`Web.URL=${process.env.WEB_URL??"http://localhost:3001"}`,`API.URL=${process.env.API_URL??"http://localhost:4001/api"}`,`Browser=Chromium`,`Node=${process.version}`,`OS=${os.platform()} ${os.release()}`,`Functional.Coverage=270 API + 100 UI + 60 BDD = 430`,`Performance.Coverage=20 scenarios`,`Combined.Coverage=450 tests`].join("\n"));
writeFileSync(`${results}/executor.json`,JSON.stringify({name:"Raja Haroon Jamal • Sr QA Automation",type:"github",buildName:"LedgerMate 360 Complete E2E",buildOrder:Date.now(),reportName:"LedgerMate 360 • Functional + Performance",url:"https://github.com/haroondhanyal/LedgerMate360"},null,2));
writeFileSync(`${results}/categories.json`,JSON.stringify([
 {name:"Authentication and access defects",matchedStatuses:["failed","broken"],messageRegex:".*(login|password|auth|unauthori|forbidden).*"},
 {name:"Finance calculation defects",matchedStatuses:["failed"],messageRegex:".*(amount|balance|budget|loan|saving|salary).*"},
 {name:"API contract defects",matchedStatuses:["failed","broken"],traceRegex:".*API-.*"},
 {name:"UI locator or rendering defects",matchedStatuses:["broken"],messageRegex:".*(locator|visible|element|strict mode).*"},
 {name:"Timeout and environment defects",matchedStatuses:["broken","failed"],messageRegex:".*(Timeout|ECONNREFUSED|browser|socket).*"},
 {name:"Product assertion defects",matchedStatuses:["failed"],messageRegex:".*expect.*"}
],null,2));
const result=spawnSync("npx",["allure","generate",results,"--clean","-o","automation/reports/allure-report"],{stdio:"inherit",env:{...process.env,...(javaHome?{JAVA_HOME:javaHome}:{})}});
if(result.status===0){
  const report="automation/reports/allure-report";copyFileSync("apps/web/public/ledger-logo.svg",`${report}/ledger-logo.svg`);
  const suitesData=JSON.parse(readFileSync(`${report}/data/suites.json`,"utf8")),leaves=[];function suiteLeaves(node){if(node.status&&node.uid)leaves.push(node);for(const child of node.children??[])suiteLeaves(child)}suiteLeaves(suitesData);
  const categoryGroups=["smoke","regression","negative"].map(name=>{const children=leaves.filter(x=>categoryOf(x.name)===name).map(x=>({...x,parentUid:`lm-${name}`}));return {uid:`lm-${name}`,name:name[0].toUpperCase()+name.slice(1),children}});
  writeFileSync(`${report}/data/categories.json`,JSON.stringify({uid:"lm-categories",name:"categories",children:categoryGroups}));
  const categoryItems=categoryGroups.map(x=>({uid:x.uid,name:x.name,statistic:{failed:x.children.filter(t=>t.status==="failed").length,broken:x.children.filter(t=>t.status==="broken").length,skipped:x.children.filter(t=>t.status==="skipped").length,passed:x.children.filter(t=>t.status==="passed").length,unknown:x.children.filter(t=>t.status==="unknown").length,total:x.children.length}}));
  writeFileSync(`${report}/widgets/categories.json`,JSON.stringify({total:leaves.length,items:categoryItems}));
  const trendFile=`${report}/widgets/categories-trend.json`,trend=existsSync(trendFile)?JSON.parse(readFileSync(trendFile,"utf8")):[];if(trend.length)trend[0].data=Object.fromEntries(categoryGroups.map(x=>[x.name,x.children.length]));writeFileSync(trendFile,JSON.stringify(trend));
  const file=`${report}/index.html`;let html=readFileSync(file,"utf8").replace(/<title>.*?<\/title>/,"<title>LedgerMate 360 • Automation Report</title>");
  const counts=Object.fromEntries(categoryGroups.map(x=>[x.name.toLowerCase(),x.children.length])),passed=leaves.filter(x=>x.status==="passed").length;
  html=html.replace("</body>",`<style>body{padding-top:124px!important}.side-nav{top:124px!important;height:calc(100% - 124px)!important}#lm-brand{position:fixed;inset:0 0 auto;height:112px;z-index:9999;display:flex;align-items:center;justify-content:flex-start;gap:22px;background:linear-gradient(105deg,#071b2c,#0b806e);padding:8px 36px;box-shadow:0 6px 24px #0005;font:700 25px Arial;color:#fff}#lm-brand img{width:94px;height:94px;object-fit:contain;background:#fff;border-radius:18px;padding:6px}#lm-brand small{font-size:13px;color:#b8f5e5;letter-spacing:2px}#lm-summary{position:fixed;right:24px;top:128px;z-index:9998;width:320px;background:#fff;border:1px solid #dce8e4;border-radius:16px;padding:16px;box-shadow:0 8px 28px #0002;font:13px Arial;color:#19324d}#lm-summary h3{margin:0 0 4px;font-size:17px}#lm-summary p{margin:3px 0 12px;color:#55706a}#lm-summary .lm-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}#lm-summary b{display:block;background:#eafaf5;border-radius:10px;padding:10px 4px;text-align:center;font-size:18px;color:#08765f}#lm-summary b small{display:block;font-size:10px;color:#456b63}#lm-summary .evidence{margin-top:12px;padding-top:10px;border-top:1px solid #dce8e4;font-size:12px;line-height:1.6}@media(max-width:640px){body{padding-top:88px!important}.side-nav{top:88px!important;height:calc(100% - 88px)!important}#lm-brand{height:80px;padding:5px 12px;gap:12px;font-size:19px}#lm-brand img{width:68px;height:68px}#lm-brand small{font-size:9px;letter-spacing:1px}#lm-summary{top:94px;width:min(300px,calc(100vw - 32px));right:16px}}</style><div id="lm-brand"><img src="ledger-logo.svg" alt="LedgerMate 360 logo"><span>LedgerMate 360<br><small>COMPLETE PRODUCT AUTOMATION</small></span></div><aside id="lm-summary"><h3>Coverage categories & trend</h3><p>Raja Haroon Jamal · Sr QA Automation</p><div class="lm-grid"><b>${counts.smoke}<small>SMOKE</small></b><b>${counts.regression}<small>REGRESSION</small></b><b>${counts.negative}<small>NEGATIVE</small></b></div><div class="evidence"><strong>${passed} passed · ${leaves.length-passed} failed</strong><br>Functional 430 · Performance 20<br>Open any test → direct Evidence attachments</div></aside><script>function lmView(){const h=location.hash;document.getElementById('lm-summary').style.display=(!h||h==='#/'||h.startsWith('#/overview'))?'block':'none'}addEventListener('hashchange',lmView);lmView()</script></body>`);writeFileSync(file,html);
}
process.exit(result.status??1);
