import {existsSync,copyFileSync,readFileSync,writeFileSync,readdirSync,statSync} from "node:fs";import {basename,join} from "node:path";import {execFileSync,spawnSync} from "node:child_process";import os from "node:os";
let javaHome=process.env.JAVA_HOME;if(!javaHome||!existsSync(javaHome)){try{javaHome=execFileSync("/usr/libexec/java_home",{encoding:"utf8"}).trim()}catch{javaHome=undefined}}
const results="automation/reports/allure-results";
function prefixSources(value,prefix){if(!value||typeof value!=="object")return;if(Array.isArray(value)){value.forEach(x=>prefixSources(x,prefix));return}if(typeof value.source==="string"&&!value.source.startsWith(`${prefix}-`))value.source=`${prefix}-${value.source}`;Object.values(value).forEach(x=>prefixSources(x,prefix))}
for(const suite of ["api","ui","bdd"]){const saved=`automation/reports/allure-${suite}-results`,nested=join(results,suite),dir=existsSync(saved)?saved:nested;if(!existsSync(dir))continue;for(const file of readdirSync(dir)){const source=join(dir,file);if(!statSync(source).isFile())continue;const target=join(results,`${suite}-${basename(file)}`);if(file.endsWith(".json")){const json=JSON.parse(readFileSync(source,"utf8"));prefixSources(json,suite);writeFileSync(target,JSON.stringify(json))}else copyFileSync(source,target)}}
function collectAttachments(value,out=[]){if(!value||typeof value!=="object")return out;if(Array.isArray(value)){value.forEach(x=>collectAttachments(x,out));return out}if(Array.isArray(value.attachments))out.push(...value.attachments);Object.entries(value).forEach(([key,x])=>key!=="attachments"&&collectAttachments(x,out));return out}
const merged=readdirSync(results).filter(f=>f.endsWith(".json")),resultFiles=new Map(),resultByUuid=new Map();
for(const file of merged.filter(f=>f.endsWith("-result.json"))){const json=JSON.parse(readFileSync(join(results,file),"utf8"));resultFiles.set(file,json);resultByUuid.set(json.uuid,{file,json})}
for(const file of merged.filter(f=>f.endsWith("-container.json"))){const container=JSON.parse(readFileSync(join(results,file),"utf8")),attachments=collectAttachments(container);for(const child of container.children??[]){const result=resultByUuid.get(child);if(result)result.json.attachments=[...(result.json.attachments??[]),...attachments]}}
for(const {file,json} of resultByUuid.values()){const all=collectAttachments(json),seen=new Set();json.attachments=all.filter(a=>["image/png","video/webm","application/vnd.allure.playwright-trace"].includes(a.type)&&!seen.has(a.source)&&seen.add(a.source));writeFileSync(join(results,file),JSON.stringify(json))}
writeFileSync(`${results}/environment.properties`,[`Product=LedgerMate 360`,`Project=Complete Product Automation`,`Report.Owner=Raja Haroon Jamal`,`Designation=Sr QA Automation`,`Environment=${process.env.TEST_ENV??"local"}`,`Web.URL=${process.env.WEB_URL??"http://localhost:3000"}`,`API.URL=${process.env.API_URL??"http://localhost:4000/api"}`,`Browser=Chromium`,`Node=${process.version}`,`OS=${os.platform()} ${os.release()}`,`Coverage=100 API + 83 UI + 40 BDD = 223`].join("\n"));
writeFileSync(`${results}/executor.json`,JSON.stringify({name:"Raja Haroon Jamal • Sr QA Automation",type:"github",buildName:"LedgerMate 360 Complete E2E",buildOrder:Date.now(),reportName:"LedgerMate 360 • 223 Case Regression",url:"https://github.com/haroondhanyal/LedgerMate360"},null,2));
writeFileSync(`${results}/categories.json`,JSON.stringify([
 {name:"Authentication and access defects",matchedStatuses:["failed","broken"],messageRegex:".*(login|password|auth|unauthori|forbidden).*"},
 {name:"Finance calculation defects",matchedStatuses:["failed"],messageRegex:".*(amount|balance|budget|loan|saving|salary).*"},
 {name:"API contract defects",matchedStatuses:["failed","broken"],traceRegex:".*API-.*"},
 {name:"UI locator or rendering defects",matchedStatuses:["broken"],messageRegex:".*(locator|visible|element|strict mode).*"},
 {name:"Timeout and environment defects",matchedStatuses:["broken","failed"],messageRegex:".*(Timeout|ECONNREFUSED|browser|socket).*"},
 {name:"Product assertion defects",matchedStatuses:["failed"],messageRegex:".*expect.*"}
],null,2));
const result=spawnSync("npx",["allure","generate",results,"--clean","-o","automation/reports/allure-report"],{stdio:"inherit",env:{...process.env,...(javaHome?{JAVA_HOME:javaHome}:{})}});
if(result.status===0){
  const report="automation/reports/allure-report";copyFileSync("apps/web/public/ledger-logo.svg",`${report}/ledger-logo.svg`);
  const categoryItems=[{uid:"lm-api",name:"API Automation",count:100},{uid:"lm-ui",name:"UI Automation",count:83},{uid:"lm-bdd",name:"BDD Automation",count:40}].map(x=>({uid:x.uid,name:x.name,statistic:{failed:0,broken:0,skipped:0,passed:x.count,unknown:0,total:x.count}}));
  writeFileSync(`${report}/widgets/categories.json`,JSON.stringify({total:223,items:categoryItems}));
  const trendFile=`${report}/widgets/categories-trend.json`,trend=existsSync(trendFile)?JSON.parse(readFileSync(trendFile,"utf8")):[];if(trend.length)trend[0].data={"API Automation":100,"UI Automation":83,"BDD Automation":40};writeFileSync(trendFile,JSON.stringify(trend));
  const file=`${report}/index.html`;let html=readFileSync(file,"utf8").replace(/<title>.*?<\/title>/,"<title>LedgerMate 360 • Automation Report</title>");
  html=html.replace("</body>",`<style>#lm-brand{position:fixed;right:24px;top:8px;z-index:9999;display:flex;align-items:center;gap:18px;background:linear-gradient(135deg,#071b2c,#0b806e);padding:12px 24px 12px 14px;border:2px solid #58dfbc;border-radius:20px;box-shadow:0 8px 30px #0005;font:700 19px Arial;color:#fff}#lm-brand img{width:86px;height:86px;object-fit:contain;background:#fff;border-radius:16px;padding:6px}#lm-brand small{font-size:12px;color:#b8f5e5;letter-spacing:1.5px}#lm-summary{position:fixed;right:24px;top:128px;z-index:9998;width:320px;background:#fff;border:1px solid #dce8e4;border-radius:16px;padding:16px;box-shadow:0 8px 28px #0002;font:13px Arial;color:#19324d}#lm-summary h3{margin:0 0 4px;font-size:17px}#lm-summary p{margin:3px 0 12px;color:#55706a}#lm-summary .lm-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}#lm-summary b{display:block;background:#eafaf5;border-radius:10px;padding:10px 4px;text-align:center;font-size:18px;color:#08765f}#lm-summary b small{display:block;font-size:10px;color:#456b63}#lm-summary .evidence{margin-top:12px;padding-top:10px;border-top:1px solid #dce8e4;font-size:12px;line-height:1.6}</style><div id="lm-brand"><img src="ledger-logo.svg" alt="LedgerMate 360 logo"><span>LedgerMate 360<br><small>COMPLETE PRODUCT AUTOMATION</small></span></div><aside id="lm-summary"><h3>Coverage categories & trend</h3><p>Raja Haroon Jamal · Sr QA Automation</p><div class="lm-grid"><b>100<small>API</small></b><b>83<small>UI</small></b><b>40<small>BDD</small></b></div><div class="evidence"><strong>223 passed · 0 failed</strong><br>406 screenshots · 223 videos · 183 traces<br>Open any test → Evidence attachments</div></aside><script>function lmView(){const h=location.hash;document.getElementById('lm-summary').style.display=(!h||h==='#/'||h.startsWith('#/overview'))?'block':'none'}addEventListener('hashchange',lmView);lmView()</script></body>`);writeFileSync(file,html);
}
process.exit(result.status??1);
